FROM eclipse-temurin:17-jdk
EXPOSE 8080
ARG JAR_FILE=./build/libs/*-SNAPSHOT.jar
ARG JASYPT_ENCRYPTOR_PASSWORD

COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java", "-jar","-Duser.timezone=Asia/Seoul", "-Dspring.profiles.active=dev","app.jar"]
