FROM openjdk:17
EXPOSE 8080
ARG JAR_FILE=./build/libs/*-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar

RUN mkdir -p /home/ubuntu/staccato/logs

ENTRYPOINT ["java", "-jar","-Duser.timezone=Asia/Seoul", "-Dspring.profiles.active=prod","app.jar"]
