FROM openjdk:17
EXPOSE 8080 8081
ARG JAR_FILE=./build/libs/*-SNAPSHOT.jar
ARG JASYPT_ENCRYPTOR_PASSWORD

COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java", "-jar","-Duser.timezone=Asia/Seoul", "-Dspring.profiles.active=prod","app.jar"]
