spring:
  config:
    activate:
      on-profile: local
  application:
    name: staccato
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    writer:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: staccato
      password: 1234
      jdbc-url: jdbc:mysql://localhost:3307/staccato?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    reader:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: staccato
      password: 1234
      jdbc-url: jdbc:mysql://localhost:3305/staccato?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        create_empty_composites.enabled: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
  admin:
    key: ${ADMIN_KEY}
    token: ${ADMIN_TOKEN}
cloud:
  aws:
    s3:
      bucket: techcourse-project-2024
      endpoint: https://techcourse-project-2024.s3.ap-northeast-2.amazonaws.com
    cloudfront:
      endpoint: https://d25aribbn0gp8k.cloudfront.net
    region:
      static: ap-northeast-2
    stack:
      auto: false
image:
  folder:
    name: image/
