spring:
  config:
    activate:
      on-profile: local
  application:
    name: staccato
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:staccato
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
cloud:
  aws:
    s3:
      bucket: techcourse-project-2024
      endpoint: https://techcourse-project-2024.s3.ap-northeast-2.amazonaws.com
    cloudfront:
      endpoint: https://d25aribbn0gp8k.cloudfront.net
    region:
      static: ap-northeast-2
    stack:
      auto: false
