name: Android CI for generating APK

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./android/Staccato_AN

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Create local.properties
        run: |
          touch local.properties
        shell: bash

      - name: Set Base Url in local.properties
        run: |
          echo "base_url=\"$BASE_URL\"" >> local.properties
        shell: bash

      - name: Create google-services.json
        run: |
          echo '${{GOOGLE_SERVICES_JSON}}' > ./app/google-services.json
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
