name: Backend CI/CD prod

on:
  push:
    paths: [ 'backend/**', '.github/**' ]
    branches: [ "release-be" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./backend

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup with Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}

      - name: Docker Image Build
        run: |
          sudo docker build --platform linux/arm64 -t staccato/staccato:prod -f Dockerfile.prod .

      - name: Docker Hub Push
        run: |
          sudo docker login --username ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }} --password ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}
          sudo docker push staccato/staccato:prod

  cd:
    needs: ci
    runs-on: [ self-hosted, prod ]

    strategy:
      matrix:
        runner: [ prod-a, prod-b ]

    steps:
      - name: execute deploy.sh
        run: bash /home/ubuntu/staccato/deploy.sh
