name: Android CI

on:
  push:
    branches: [ "develop-an" ]
  pull_request:
    branches: [ "develop-an" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Clean build
        run: ./gradlew clean build

      - name: Clean test
        run: ./gradlew clean test

      - name: Build with Gradle
        run: ./gradlew build
