name: Check if feature branch is up to date with develop

on:
  pull_request:
    branches:
      - develop

jobs:
  check-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # merge-base 검사 위해 전체 히스토리 필요

      - name: Fetch develop
        run: git fetch origin develop

      - name: Check if develop is merged into feature
        run: |
          git merge-base --is-ancestor origin/develop HEAD
        # HEAD = PR 브랜치 커밋
        # origin/develop이 HEAD의 조상이라면 최신 develop을 머지한 것

      - name: Fail if not up-to-date
        if: failure()
        run: |
          echo "::error::❌ 이 브랜치는 최신 develop을 포함하고 있지 않습니다. 먼저 'git merge origin/develop'을 해주세요."
          exit 1
